# $ sudo docker-compose build
# $ sudo docker-compose up
# $ sudo docker-compose run web <command>

version: '3'
# Задеплоить изменения с возможностью редактировать эвенты (скорее всего дело в dist, перебилдить)
services:
  db:
    image: postgres:12.0
    environment:
        POSTGRES_DB: event_manager_db
        POSTGRES_USER: jornojovana
        POSTGRES_PASSWORD: jornojovana
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
  web:
    build: .
    env_file:
      - event-manager.env
    command: gunicorn event_manager.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    image: redis:alpine
    expose:
      - 6379
  celery:
    build: .
    command: celery -A event_manager worker -B -l info
    volumes:
      - .:/code
    env_file:
      - event-manager.env
    depends_on:
      - redis



volumes:
  postgres_data:
