# Generated by Django 3.0.4 on 2020-05-21 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_time_created']},
        ),
        migrations.AddField(
            model_name='event',
            name='event_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 14, 36, 55, 766049, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='default-value', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
