# Generated by Django 3.0.4 on 2020-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200521_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
