# Generated by Django 3.0.4 on 2020-06-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200525_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['-title']},
        ),
    ]
