# Generated by Django 3.0.4 on 2020-06-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20200609_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
