# Generated by Django 3.0.4 on 2020-06-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20200611_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
