# Generated by Django 3.0.4 on 2020-06-13 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20200611_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator('^[\\w\\s]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
