# Generated by Django 3.0.7 on 2020-06-19 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20200613_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[\\w\\s]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
